// Mocks generated by Mockito 5.4.6 from annotations
// in fake_store/test/unit/home_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fake_store/core/networking/api_result.dart' as _i3;
import 'package:fake_store/core/usecases/usecase.dart' as _i7;
import 'package:fake_store/features/home/domain/entities/category.dart' as _i9;
import 'package:fake_store/features/home/domain/entities/product.dart' as _i6;
import 'package:fake_store/features/home/domain/repo/home_repo.dart' as _i2;
import 'package:fake_store/features/home/domain/usecases/get_all_categories.dart'
    as _i8;
import 'package:fake_store/features/home/domain/usecases/get_all_products.dart'
    as _i4;
import 'package:fake_store/features/home/domain/usecases/get_category_products.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHomeRepo_0 extends _i1.SmartFake implements _i2.HomeRepo {
  _FakeHomeRepo_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiResult_1<T> extends _i1.SmartFake implements _i3.ApiResult<T> {
  _FakeApiResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllProducts extends _i1.Mock implements _i4.GetAllProducts {
  @override
  _i2.HomeRepo get homeRepo =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepo),
            returnValue: _FakeHomeRepo_0(this, Invocation.getter(#homeRepo)),
            returnValueForMissingStub: _FakeHomeRepo_0(
              this,
              Invocation.getter(#homeRepo),
            ),
          )
          as _i2.HomeRepo);

  @override
  _i5.Future<_i3.ApiResult<List<_i6.Product>>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.ApiResult<List<_i6.Product>>>.value(
              _FakeApiResult_1<List<_i6.Product>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.ApiResult<List<_i6.Product>>>.value(
                  _FakeApiResult_1<List<_i6.Product>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.ApiResult<List<_i6.Product>>>);
}

/// A class which mocks [GetAllCategories].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategories extends _i1.Mock implements _i8.GetAllCategories {
  @override
  _i2.HomeRepo get homeRepo =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepo),
            returnValue: _FakeHomeRepo_0(this, Invocation.getter(#homeRepo)),
            returnValueForMissingStub: _FakeHomeRepo_0(
              this,
              Invocation.getter(#homeRepo),
            ),
          )
          as _i2.HomeRepo);

  @override
  _i5.Future<_i3.ApiResult<List<_i9.Category>>> call(_i7.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.ApiResult<List<_i9.Category>>>.value(
              _FakeApiResult_1<List<_i9.Category>>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.ApiResult<List<_i9.Category>>>.value(
                  _FakeApiResult_1<List<_i9.Category>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.ApiResult<List<_i9.Category>>>);
}

/// A class which mocks [GetCategoryProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoryProducts extends _i1.Mock
    implements _i10.GetCategoryProducts {
  @override
  _i2.HomeRepo get homeRepo =>
      (super.noSuchMethod(
            Invocation.getter(#homeRepo),
            returnValue: _FakeHomeRepo_0(this, Invocation.getter(#homeRepo)),
            returnValueForMissingStub: _FakeHomeRepo_0(
              this,
              Invocation.getter(#homeRepo),
            ),
          )
          as _i2.HomeRepo);

  @override
  _i5.Future<_i3.ApiResult<List<_i6.Product>>> call(String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#call, [categoryName]),
            returnValue: _i5.Future<_i3.ApiResult<List<_i6.Product>>>.value(
              _FakeApiResult_1<List<_i6.Product>>(
                this,
                Invocation.method(#call, [categoryName]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.ApiResult<List<_i6.Product>>>.value(
                  _FakeApiResult_1<List<_i6.Product>>(
                    this,
                    Invocation.method(#call, [categoryName]),
                  ),
                ),
          )
          as _i5.Future<_i3.ApiResult<List<_i6.Product>>>);
}
